"""empty message

Revision ID: c233c5ebfcbb
Revises: 7c1fa152f008
Create Date: 2022-11-02 13:39:57.978943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c233c5ebfcbb'
down_revision = '7c1fa152f008'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookstores', sa.Column('previewImage', sa.String(length=500), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookstores', 'previewImage')
    # ### end Alembic commands ###
